name: Dependency-track

on:
  push:

jobs:
  checkout-repo:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name : uploading the results
      run : |
        pip install cyclonedx-bom  
        cyclonedx-py -r -i requirements.txt -o bom.xml
        python3 upload.py
      env:
        URL: ${{ secrets.URL}}
        KEY: ${{ secrets.KEY }}
